[package]
name = "shoot"
version = "0.1.0"
authors = ["Khoa Do <happyboy0412@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.sdl2]
version = "0.32"
default-features = false
features = ["ttf","image"]
